default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PRACTICE_DATABASE_USER'] %>
  password: <%= ENV['PRACTICE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: practice_development

test:
  <<: *default
  database: practice_test

production:
  <<: *default
  database: practice_production